const LOGIN_IN  = 'LOGIN_IN'
const LOGIN_OUT = 'LOGIN_OUT'
const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
const LOGIN_FAIL = 'LOGIN_FAIL'

export default {
  LOGIN_FAIL,
  LOGIN_SUCCESS,
  LOGIN_IN,
  LOGIN_OUT
}